import { Language } from './useLanguage';

export interface TranslationStrings {
  nav: { home: string; products: string; shisha: string; bbq: string; oem: string; quality: string; export: string; about: string; blog: string; contact: string; };
  hero: { title: string; subtitle: string; cta1: string; cta2: string; };
  common: { learnMore: string; getSample: string; contactUs: string; viewSpecs: string; freeSample: string; wholesale: string; factory: string; manufacturer: string; exporter: string; seeMore: string; };
  footer: { description: string; products: string; company: string; getInTouch: string; shisha: string; bbq: string; oem: string; quality: string; export: string; about: string; contact: string; allRights: string; };
  products: { 
    title: string; subtitle: string; shishaName: string; shishaDesc: string; bbqName: string; bbqDesc: string; burnTime: string; ashContent: string; noOdor: string; heatValue: string;
    heroTitle: string; heroDesc: string;
    shishaSub: string; bbqSub: string;
    shishaFeature1: string; shishaFeature2: string; shishaFeature3: string; shishaFeature4: string; shishaFeature5: string; shishaFeature6: string;
    bbqFeature1: string; bbqFeature2: string; bbqFeature3: string; bbqFeature4: string; bbqFeature5: string; bbqFeature6: string;
    qualityGrades: string; qualityGradesDesc: string;
    standard: string; standardDesc: string; premium: string; premiumDesc: string; super: string; superDesc: string; popular: string;
    burn2: string; burn3: string; burn4: string; moisture1: string; moisture2: string; moisture3: string; carbon1: string; carbon2: string; carbon3: string;
    oemTitle: string; oemDesc: string; oem1: string; oem2: string; oem3: string; ctaDesc: string;
  };
  about: { title: string; subtitle: string; description: string; yearsExp: string; tonsExported: string; countries: string; iso: string; halal: string; eco: string; labTested: string; productionCapacity: string; exportCountries: string; clients: string; factoryTitle: string; factoryDesc: string; modernEquip: string; modernEquipDesc: string; qcCert: string; qcCertDesc: string; globalReady: string; globalReadyDesc: string; whyIndo: string; richPotassium: string; richPotassiumDesc: string; highCarbon: string; highCarbonDesc: string; odorless: string; odorlessDesc: string; sustainable: string; sustainableDesc: string; visitFactory: string; visitFactoryDesc: string; };
  contact: { title: string; subtitle: string; cta: string; whatsapp: string; email: string; yourName: string; yourEmail: string; yourMessage: string; send: string; openingEmail: string; getQuote: string; readyOrder: string; factoryLocation: string; phone: string; responseTime: string; within24: string; sendMessage: string; formDesc: string; company: string; country: string; messagePlaceholder: string; sending: string; thankYou: string; preferWA: string; WADesc: string; seoDesc: string; };
  whyChoose: { title: string; subtitle: string; problem: string; butFinding: string; description: string; onTime: string; onTimeDesc: string; docs: string; docsDesc: string; logistics: string; logisticsDesc: string; quality: string; qualityDesc: string; downloadProfile: string; };
  pages: { about: string; products: string; oem: string; quality: string; export: string; blog: string; contact: string; };
  oem: { charcoalMfg: string; createBrand: string; howItWorks: string; requestQuote: string; whyPartner: string; confidential: string; confidentialDesc: string; design: string; designDesc: string; packaging: string; packagingDesc: string; docs: string; docsDesc: string; oemProcess: string; inquiry: string; inquiryDesc: string; sample: string; sampleDesc: string; design2: string; design2Desc: string; production: string; productionDesc: string; shipping: string; shippingDesc: string; packagingOptions: string; innerBox: string; masterBox: string; plastic: string; sizes: string; features: string; fullColor: string; lamination: string; embossing: string; colorPrint: string; uv: string; customSize: string; heatSeal: string; zipLock: string; standPouch: string; variousSizes: string; customPrint: string; brandSafe: string; brandSafeDesc: string; signedNDA: string; dedicatedLine: string; designConf: string; startBrand: string; startBrandDesc: string; contactOEM: string; };
  quality: { title: string; subtitle: string; cta: string; viewQC: string; requestReports: string; intCert: string; iso: string; isoDesc: string; exportLic: string; exportLicDesc: string; factoryAudit: string; factoryAuditDesc: string; msds: string; msdsDesc: string; qcProcess: string; qcProcessDesc: string; rawMaterial: string; rawMaterialDesc: string; carbonization: string; carbonizationDesc: string; grinding: string; grindingDesc: string; mixing: string; mixingDesc: string; pressing: string; pressingDesc: string; drying: string; dryingDesc: string; testing: string; testingDesc: string; finalInspect: string; finalInspectDesc: string; labTesting: string; labTestingDesc: string; ashContent: string; ashContentDesc: string; moisture: string; moistureDesc: string; fixedCarbon: string; fixedCarbonDesc: string; calorific: string; calorificDesc: string; thirdParty: string; thirdPartyDesc: string; thirdPartyCTA: string; reqDocs: string; reqDocsDesc: string; };
  export: { title: string; subtitle: string; cta: string; viewShipping: string; getQuote: string; country: string; port: string; transit: string; containerType: string; capacity: string; dims: string; prodTime: string; prodTimeDesc: string; loadingPort: string; loadingPortDesc: string; payment: string; paymentDesc: string; tt: string; ttDesc: string; lc: string; lcDesc: string; paymentDetails: string; docs: string; doc1: string; doc2: string; doc3: string; doc4: string; doc5: string; doc6: string; doc7: string; moq: string; moqDesc: string; fcl: string; lcl: string; fclDesc: string; lclDesc: string; readyOrder: string; contactSales: string; };
  blog: { title: string; subtitle: string; cta: string; allPosts: string; noArticles: string; checkBack: string; stayUpdated: string; stayUpdatedDesc: string; enterEmail: string; subscribing: string; subscribe: string; success: string; orContact: string; privacy: string; readMore: string; minRead: string; };
  keywords: string[];
}

const translations: Record<Language, TranslationStrings> = {
  en: {
    nav: { home: 'Home', products: 'Products', shisha: 'Shisha Charcoal', bbq: 'BBQ Charcoal', oem: 'OEM', quality: 'Quality', export: 'Export', about: 'About', blog: 'Blog', contact: 'Contact Us' },
hero: { title: "Indonesia 's #1 Coconut Charcoal Manufacturer", subtitle: 'The World Most Trusted Coconut Charcoal Briquettes Factory', cta1: 'View Products', cta2: 'Get Free Sample' },
    common: { learnMore: 'Learn More', getSample: 'Get Free Sample', contactUs: 'Contact Us', viewSpecs: 'View Specifications', freeSample: 'Free Sample', wholesale: 'Wholesale', factory: 'Factory', manufacturer: 'Trusted by 50+ importers across 15+ countries — from the U.S. to Saudi Arabia, Germany to Australia — we supply consistent, export-ready coconut charcoal made from 100% natural coconut shell. No additives. No shortcuts. Just reliable quality, every order.', exporter: 'Exporter', seeMore: 'See More' },
    footer: { description: "Indonesia's finest shisha & bbq coconut charcoal factory.", products: 'Products', company: 'Company', getInTouch: 'Get in Touch', shisha: 'Shisha Charcoal', bbq: 'BBQ Charcoal', oem: 'OEM Services', quality: 'Quality', export: 'Export Info', about: 'About Us', contact: 'Contact', allRights: 'All rights reserved.' },
    products: { 
    title: 'Our Products', subtitle: 'Two product lines. One uncompromising standard.', shishaName: 'Shisha Charcoal', shishaDesc: 'Long, clean burn. Minimal ash. Zero chemical taste. Made from 100% natural coconut shell for a smooth session from first puff to last.', bbqName: 'BBQ Charcoal', bbqDesc: 'Ignites quickly, burns longer than wood charcoal, and produces clean neutral smoke — letting the food speak for itself. Built for restaurants, retail brands & private label.', burnTime: 'Burn Time', ashContent: 'Ash Content', noOdor: 'No Odor', heatValue: 'Heat Value',
    heroTitle: 'Premium Coconut Charcoal', heroDesc: 'High-quality coconut shell charcoal for shisha and BBQ.',
    shishaSub: 'Premium hookah coals for wholesale buyers', bbqSub: 'Premium grilling charcoal for global markets',
    shishaFeature1: '2+ hours burning time', shishaFeature2: 'Ash content 1.6% - 2.5%', shishaFeature3: '650°C burning temperature', shishaFeature4: 'Odorless & chemical-free', shishaFeature5: 'Multiple shapes available', shishaFeature6: 'OEM packaging supported',
    bbqFeature1: 'High heat output', bbqFeature2: 'Long-lasting burn', bbqFeature3: 'Low ash production', bbqFeature4: 'Natural coconut flavor', bbqFeature5: 'Easy ignition', bbqFeature6: 'Eco-friendly',
    qualityGrades: 'Quality Grades', qualityGradesDesc: 'We offer three quality tiers to meet different budget and quality requirements.',
    standard: 'Standard', standardDesc: 'Entry level quality', premium: 'Premium', premiumDesc: 'Best value for money', super: 'Super Premium', superDesc: 'Luxury brand quality', popular: 'MOST POPULAR',
    burn2: '2+ hours', burn3: '2.5+ hours', burn4: '3+ hours', moisture1: 'Moisture 6-8%', moisture2: 'Moisture 5-7%', moisture3: 'Moisture 4-6%', carbon1: 'Fixed carbon 75%', carbon2: 'Fixed carbon 78%', carbon3: 'Fixed carbon 80%',
    oemTitle: 'OEM & Private Label', oemDesc: 'We help brands establish their own charcoal line with custom packaging.', oem1: 'Full confidentiality & NDA', oem2: 'Custom box design support', oem3: 'Multiple packaging options', ctaDesc: 'Contact us for a free sample and competitive quote.',
  },
    about: { title: 'About Us', subtitle: 'A decade of crafting charcoal the world relies on.', description: "Mono Charcoal (PT. Mono Milik Nusantara) served worldwide from 2016 with one clear purpose — to produce the finest coconut charcoal briquettes Indonesia has to offer. Built on nearly a decade of hands-on expertise, our factory combines time-tested craftsmanship with rigorous quality control to deliver premium briquettes for shisha and BBQ brands worldwide.\n\nEvery batch starts with carefully selected coconut shells, processed through a manufacturing method refined over thousands of export orders. We don't just supply charcoal — we supply consistency, reliability, and the kind of quality your customers will notice on the first light.", yearsExp: 'Years Experience', tonsExported: 'Tons Exported / Month', countries: 'Countries Served', iso: 'ISO Certified', halal: 'Full Documentation', eco: 'Eco-Friendly', labTested: 'Lab Tested', productionCapacity: 'Production Capacity', exportCountries: 'Export Countries', clients: 'Clients Served', factoryTitle: 'Our Factory', factoryDesc: 'Modern facility.', modernEquip: 'Modern Equipment', modernEquipDesc: 'Industrial machinery.', qcCert: 'Quality Certified', qcCertDesc: 'ISO certified.', globalReady: 'Global Export Ready', globalReadyDesc: 'International shipping.', whyIndo: 'Why Indonesian?', richPotassium: 'Rich in Potassium', richPotassiumDesc: 'High potassium content.', highCarbon: 'High Carbon', highCarbonDesc: '75-80% carbon.', odorless: 'Odorless', odorlessDesc: '100% natural.', sustainable: 'Sustainable', sustainableDesc: 'Indonesia largest producer.', visitFactory: 'Visit Our Factory', visitFactoryDesc: 'Welcome to visit.' },
    contact: { title: 'Contact Us', subtitle: 'Ready to Order?', cta: 'Contact us today.', whatsapp: 'Chat on WhatsApp', email: 'admin@monocharcoal.com', yourName: 'Your Name', yourEmail: 'Your Email', yourMessage: 'Your Message', send: 'Send Message', openingEmail: 'Opening email...', getQuote: 'Get Your Quote', readyOrder: 'Ready to order?', factoryLocation: 'Factory Location', phone: 'Phone', responseTime: 'Response Time', within24: 'Within 24 hours', sendMessage: 'Send a Message', formDesc: 'We respond within 24 hours.', company: 'Company', country: 'Country', messagePlaceholder: 'Your requirements', sending: 'Sending...', thankYou: 'Thank you! Message sent.', preferWA: 'Prefer WhatsApp?', WADesc: 'Fast response on WhatsApp.', seoDesc: 'Contact us for free sample.' },
    whyChoose: { title: 'Why Mono Charcoal', subtitle: 'Finding a factory in Indonesia is easy.', problem: 'Indonesia produces best...', butFinding: "Finding one you can actually build a business with — that's the hard part.", description: 'There are hundreds of charcoal suppliers in Indonesia. Very few have the consistency, transparency, and long-term commitment that serious importers need.', onTime: 'On-Time Production', onTimeDesc: 'We plan every production run around your shipment schedule. With a structured process and reliable raw material supply, we hit agreed timelines consistently — so your supply chain never waits on us.', docs: 'Full Documentation', docsDesc: 'From certificates of origin to quality inspection reports and customs documents — we handle the full paperwork stack so your imports clear without friction. No chasing, no surprises, no port delays.', logistics: 'Managed Logistics', logisticsDesc: 'We coordinate freight, container loading, and export handling from our facility to your destination — FCL or LCL. We work with trusted freight partners so your order arrives on time and in perfect condition.', quality: 'Consistent Quality', qualityDesc: "Every batch goes through the same selection process, the same production standards, the same quality checks — whether it's your first order or your fiftieth. We only ship charcoal we'd stake our reputation on.", downloadProfile: 'Download Company Profile' },
    pages: { about: 'About', products: 'Products', oem: 'OEM', quality: 'Quality', export: 'Export', blog: 'Blog', contact: 'Contact Us' },
    oem: { charcoalMfg: 'Charcoal Manufacturing', createBrand: 'Create your own brand.', howItWorks: 'How It Works', requestQuote: 'Request Quote', whyPartner: 'Why Partner?', confidential: 'Full Confidentiality', confidentialDesc: 'NDA protection.', design: 'Custom Design', designDesc: 'Your brand packaging.', packaging: 'Packaging Options', packagingDesc: 'Various options.', docs: 'Complete Docs', docsDesc: 'Export certifications.', oemProcess: 'OEM Process', inquiry: 'Inquiry', inquiryDesc: 'Send requirements', sample: 'Sample', sampleDesc: 'Sample approval', design2: 'Design', design2Desc: 'Package design', production: 'Production', productionDesc: 'Full production', shipping: 'Shipping', shippingDesc: 'Worldwide delivery', packagingOptions: 'Packaging Options', innerBox: 'Inner Box', masterBox: 'Master Box', plastic: 'Plastic', sizes: 'Sizes:', features: 'Features:', fullColor: 'Full color', lamination: 'Lamination', embossing: 'Embossing', colorPrint: 'Color print', uv: 'UV coating', customSize: 'Custom size', heatSeal: 'Heat seal', zipLock: 'Zip lock', standPouch: 'Stand-up pouch', variousSizes: 'Various sizes', customPrint: 'Custom printing', brandSafe: 'Brand is Safe', brandSafeDesc: 'NDA for all.', signedNDA: 'Signed NDA', dedicatedLine: 'Dedicated line', designConf: 'Design confidentiality', startBrand: 'Start Your Brand', startBrandDesc: 'Build your private label.', contactOEM: 'Contact for OEM' },
    quality: { title: 'Quality & Certifications', subtitle: 'Quality You Can Trust', cta: 'View QC Process', viewQC: 'View QC Process', requestReports: 'Request Lab Reports', intCert: 'International Certifications', iso: 'ISO 9001:2015', isoDesc: 'Quality Management System', exportLic: 'Export License', exportLicDesc: 'Indonesian Government', factoryAudit: 'Factory Audit', factoryAuditDesc: 'Third-Party Verified', msds: 'MSDS', msdsDesc: 'Material Safety Data Sheet', qcProcess: '8-Step Quality Control', qcProcessDesc: 'Ensuring consistent quality', rawMaterial: 'Raw Material Inspection', rawMaterialDesc: 'Coconut shells tested for quality', carbonization: 'Carbonization Control', carbonizationDesc: 'Temperature and timing monitored', grinding: 'Grinding Precision', grindingDesc: 'Exact mesh size for consistency', mixing: 'Mixing Ratio', mixingDesc: 'Binder and water precisely measured', pressing: 'Pressing & Shaping', pressingDesc: 'Hydraulic pressure for density', drying: 'Drying Process', dryingDesc: 'Controlled drying for moisture', testing: 'Quality Testing', testingDesc: 'Ash content and burn time', finalInspect: 'Final Inspection', finalInspectDesc: 'Visual inspection', labTesting: 'Independent Laboratory Testing', labTestingDesc: 'Each batch tested by independent labs', ashContent: 'Ash Content', ashContentDesc: '1.6% - 2.5%', moisture: 'Moisture', moistureDesc: '4% - 8%', fixedCarbon: 'Fixed Carbon', fixedCarbonDesc: '75% - 80%', calorific: 'Calorific Value', calorificDesc: '7,500 cal/g', thirdParty: 'Third-Party Inspection', thirdPartyDesc: 'SGS, Intertek, or Bureau Veritas', thirdPartyCTA: 'Export Information', reqDocs: 'Request Quality Documentation', reqDocsDesc: 'Lab reports and certificates with every export' },
    export: { title: 'Export & Shipping', subtitle: 'Global Shipping', cta: 'View Shipping Routes', viewShipping: 'View Shipping Routes', getQuote: 'Get Shipping Quote', country: 'Country', port: 'Port', transit: 'Transit Time', containerType: 'Container Type', capacity: 'Capacity', dims: 'Dimensions', prodTime: 'Production & Delivery Time', prodTimeDesc: 'Standard lead times', loadingPort: 'Loading Ports', loadingPortDesc: 'Jakarta, Semarang, Surabaya', payment: 'Payment Terms', paymentDesc: 'Flexible options', tt: 'Telegraph Transfer (TT)', ttDesc: '50% advance, 50% before shipment', lc: 'Letter of Credit (LC)', lcDesc: 'For orders over 10 containers', paymentDetails: 'USD, EUR accepted', docs: 'Export Documentation', doc1: 'Bill of Lading', doc2: 'Commercial Invoice', doc3: 'Packing List', doc4: 'Certificate of Origin', doc5: 'Export Declaration', doc6: 'MSDS', doc7: 'Quality Certificate', moq: 'Minimum Order Quantity', moqDesc: 'Flexible order sizes', fcl: '20ft Container (FCL)', lcl: '1 ton (LCL)', fclDesc: '18-20 tons', lclDesc: 'Sample Order', readyOrder: 'Ready to Order?', contactSales: 'Contact Sales' },
    blog: { title: 'Blog', subtitle: 'Industry Insights & Guides', cta: 'Expert insights on sourcing and manufacturing.', allPosts: 'All Posts', noArticles: 'No articles yet', checkBack: 'Check back soon for new content!', stayUpdated: 'Stay Updated', stayUpdatedDesc: 'Subscribe for latest industry insights and business guides.', enterEmail: 'Enter your email', subscribing: 'Subscribing...', subscribe: 'Subscribe', success: 'Thank you for subscribing!', orContact: 'Or contact us on WhatsApp', privacy: 'We respect your privacy. Unsubscribe at any time.', readMore: 'Read Article', minRead: 'min read' },
    keywords: ['shisha charcoal', 'BBQ charcoal']
  },
  ar: {
    nav: { home: 'الرئيسية', products: 'المنتجات', shisha: 'فحم الشيشة', bbq: 'فحم الشواء', oem: 'تصنيع', quality: 'الجودة', export: 'التصدير', about: 'عن الشركة', blog: 'المدونة', contact: 'اتصل بنا' },
    hero: { title: 'فحم قشر جوز الهند', subtitle: 'من إندونيسيا للعالم', cta1: 'شاهد المنتجات', cta2: 'احصل على عينة' },
    common: { learnMore: 'اعرف المزيد', getSample: 'عينة مجانية', contactUs: 'اتصل بنا', viewSpecs: 'المواصفات', freeSample: 'عينة مجانية', wholesale: 'بالجملة', factory: 'مصنع', manufacturer: 'مصنّع', exporter: 'مصدّر', seeMore: 'المزيد' },
    footer: { description: 'أفضل مصنع فحم إندونيسيا', products: 'المنتجات', company: 'الشركة', getInTouch: 'تواصل معنا', shisha: 'فحم الشيشة', bbq: 'فحم الشواء', oem: 'التصنيع', quality: 'الجودة', export: 'التصدير', about: 'عن الشركة', contact: 'اتصل بنا', allRights: 'جميع الحقوق محفوظة' },
    products: { 
    title: 'منتجاتنا', subtitle: 'فحم فاخر.', shishaName: 'فحم الشيشة', shishaDesc: 'فحم شيشة فاخر.', bbqName: 'فحم الشواء', bbqDesc: 'فحم شوي عالي الحرارة.', burnTime: 'مدة الاحتراق', ashContent: 'الرماد', noOdor: 'بدون رائحة', heatValue: 'الحرارة',
    heroTitle: 'فحم جوز الهند', heroDesc: 'فحم عالي الجودة للشيشة والشوي.',
    shishaSub: 'فحم شيشة للجملة', bbqSub: 'فحم شوي للعالم',
    shishaFeature1: '2+ ساعة احتراق', shishaFeature2: 'رماد 1.6% - 2.5%', shishaFeature3: '650°C', shishaFeature4: 'بدون رائحة', shishaFeature5: 'أشكال متعددة', shishaFeature6: 'دعم OEM',
    bbqFeature1: 'حرارة عالية', bbqFeature2: 'احتراق طويل', bbqFeature3: 'رماد قليل', bbqFeature4: 'نكهة طبيعية', bbqFeature5: 'إشعال سهل', bbqFeature6: 'صديق البيئة',
    qualityGrades: 'درجات الجودة', qualityGradesDesc: 'ثلاث درجات.',
    standard: 'قياسي', standardDesc: 'مستوى الدخول', premium: 'بريميوم', premiumDesc: 'أفضل قيمة', super: 'سوبر بريميوم', superDesc: 'جودة فاخرة', popular: 'الأكثر شعبية',
    burn2: '2+ ساعة', burn3: '2.5+ ساعة', burn4: '3+ ساعة', moisture1: 'رطوبة 6-8%', moisture2: 'رطوبة 5-7%', moisture3: 'رطوبة 4-6%', carbon1: 'كربون 75%', carbon2: 'كربون 78%', carbon3: 'كربون 80%',
    oemTitle: 'التصنيع تحت العلامة', oemDesc: 'نساعد العلامات.', oem1: 'سرية تامة', oem2: 'تصميم_boxes', oem3: 'خيارات متعددة', ctaDesc: 'تواصل معنا.',
  },
    about: { title: 'عن الشركة', subtitle: 'مصنع فحم إندونيسيا', description: 'مصنع ومصدّر رائد', yearsExp: 'سنوات الخبرة', tonsExported: 'أطنان مصدرة', countries: 'بلدان', iso: 'ISO', halal: 'حلال', eco: 'صديق البيئة', labTested: 'مختبر', productionCapacity: 'الطاقة', exportCountries: 'بلدان التصدير', clients: 'العملاء', factoryTitle: 'المصنع', factoryDesc: 'منشأة حديثة', modernEquip: 'معدات حديثة', modernEquipDesc: 'آلات صناعية', qcCert: 'جودة معتمدة', qcCertDesc: 'ISO معتمد', globalReady: 'جاهز للتصدير', globalReadyDesc: 'شحن دولي', whyIndo: 'لماذا إندونيسيا؟', richPotassium: 'غني بالبوتاسيوم', richPotassiumDesc: 'بوتاسيوم عالي', highCarbon: 'كربون عالي', highCarbonDesc: 'كربون 75-80%', odorless: 'بدون رائحة', odorlessDesc: 'طبيعي 100%', sustainable: 'استدامة', sustainableDesc: 'Indonesia biggest', visitFactory: 'زيارة', visitFactoryDesc: 'نرحب بزيارتكم' },
    contact: { title: 'اتصل بنا', subtitle: 'جاهز للطلب؟', cta: 'تواصل معنا', whatsapp: 'واتساب', email: 'admin@monocharcoal.com', yourName: 'اسمك', yourEmail: 'بريدك', yourMessage: 'رسالتك', send: 'إرسال', openingEmail: 'فتح البريد', getQuote: 'احصل على سعر', readyOrder: 'جاهز للطلب؟', factoryLocation: 'الموقع', phone: 'الهاتف', responseTime: 'الاستجابة', within24: '24 ساعة', sendMessage: 'أرسل رسالة', formDesc: 'نرد خلال 24 ساعة', company: 'الشركة', country: 'البلد', messagePlaceholder: 'متطلباتك', sending: 'جارٍ الإرسال', thankYou: 'شكراً!', preferWA: 'واتساب؟', WADesc: 'رد سريع', seoDesc: 'تواصل معنا' },
    whyChoose: { title: 'لماذا مونو', subtitle: 'أفضل فحم', problem: 'إندونيسيا الأفضل', butFinding: 'الصعوبة في العثور', description: 'مشكلات كثيرة', onTime: 'إنتاج في الوقت', onTimeDesc: 'عملية منظمة', docs: 'وثائق كاملة', docsDesc: 'شحن كامل', logistics: 'لوجستيات', logisticsDesc: 'تتبع كامل', quality: 'جودة', qualityDesc: 'اختبار كل دفعة', downloadProfile: 'تحميل' },
    pages: { about: 'عن الشركة', products: 'المنتجات', oem: 'تصنيع', quality: 'الجودة', export: 'التصدير', blog: 'المدونة', contact: 'اتصل بنا' },
    oem: { charcoalMfg: 'تصنيع الفحم', createBrand: 'أنشئ علامتك', howItWorks: 'كيف يعمل', requestQuote: 'اطلب سعراً', whyPartner: 'لماذا نحن؟', confidential: 'سرية تامة', confidentialDesc: 'حماية NDA', design: 'تصميم مخصص', designDesc: 'تغليف بعلامتك', packaging: 'خيارات التعبئة', packagingDesc: 'خيارات متعددة', docs: 'وثائق', docsDesc: 'تصدير كامل', oemProcess: 'العملية', inquiry: 'استفسار', inquiryDesc: 'أرسل متطلباتك', sample: 'عينة', sampleDesc: 'اعتماد العينة', design2: 'تصميم', design2Desc: 'تغليف حسب العلامة', production: 'إنتاج', productionDesc: 'إنتاج كامل', shipping: 'شحن', shippingDesc: 'تسليم عالمي', packagingOptions: 'خيارات التعبئة', innerBox: 'الصندوق الداخلي', masterBox: 'الصندوق الرئيسي', plastic: 'بلاستيك', sizes: 'الأحجام:', features: 'المميزات:', fullColor: 'ألوان كاملة', lamination: 'ألوان', embossing: ' embossing', colorPrint: 'ألوان', uv: 'طلاء UV', customSize: 'حجم مخصص', heatSeal: 'ختم حراري', zipLock: 'zip', standPouch: ' standing pouch', variousSizes: 'أحجام متعددة', customPrint: 'طباعة مخصصة', brandSafe: 'حماية العلامة', brandSafeDesc: 'اتفاق NDA', signedNDA: 'اتفاق موقع', dedicatedLine: 'خط إنتاج', designConf: 'سرية التصميم', startBrand: 'ابدأ علاماتك', startBrandDesc: 'أنشئ علامتك', contactOEM: 'تواصل للـ OEM' },
    quality: { title: 'الجودة والشهادات', subtitle: 'جودة تثق بها', cta: 'عرض عملية QC', viewQC: 'عرض عملية QC', requestReports: 'طلب التقارير', intCert: 'الشهادات الدولية', iso: 'ISO 9001:2015', isoDesc: 'نظام إدارة الجودة', exportLic: 'رخصة التصدير', exportLicDesc: 'الحكومة الإندونيسية', factoryAudit: 'تدقي�� المصنع', factoryAuditDesc: 'متحقق خارجي', msds: 'MSDS', msdsDesc: 'ورقة بيانات الأمان', qcProcess: '8 خطوات QC', qcProcessDesc: 'ضمان جودة متسقة', rawMaterial: 'تفتيش المواد', rawMaterialDesc: 'اختبار قشور جوز الهند', carbonization: 'التحكم بالتكربن', carbonizationDesc: 'مراقبة درجة الحرارة', grinding: 'الدقة في الطحن', grindingDesc: 'حجم الشبكة الصحيح', mixing: 'نسبة الخلط', mixingDesc: 'مقاييس دقيقة', pressing: 'القولبة والضغط', pressingDesc: 'ضغط هيدروليكي', drying: 'عملية التجفيف', dryingDesc: 'تجفيف متحكم', testing: 'اختبار الجودة', testingDesc: 'محتوى الرماد', finalInspect: 'الفحص النهائي', finalInspectDesc: 'فحص بصري', labTesting: 'اختبار المعامل', labTestingDesc: 'اختبار كل دفعة', ashContent: 'محتوى الرماد', ashContentDesc: '1.6% - 2.5%', moisture: 'الرطوبة', moistureDesc: '4% - 8%', fixedCarbon: 'الكربون الثابت', fixedCarbonDesc: '75% - 80%', calorific: 'القيمة الحرارية', calorificDesc: '7,500 سعر/غ', thirdParty: 'Inspection من طرف ثالث', thirdPartyDesc: 'SGS أو Intertek', thirdPartyCTA: 'معلومات التصدير', reqDocs: 'طلب الوثائق', reqDocsDesc: 'تقارير وشهادات مع كل شحنة' },
    export: { title: 'التصدير والشحن', subtitle: 'شحن عالمي', cta: 'عرض طرق الشحن', viewShipping: 'عرض طرق الشحن', getQuote: 'الحصول على عرض', country: 'الدولة', port: 'الميناء', transit: 'وقتTransit', containerType: 'نوع الحاوية', capacity: 'السعة', dims: 'الأبعاد', prodTime: 'وقت الإنتاج والتسليم', prodTimeDesc: 'أوقات التسليم', loadingPort: 'موانيء التحميل', loadingPortDesc: 'جاكرتا سمارانغ سورابايا', payment: 'شروط الدفع', paymentDesc: 'خيارات مرنة', tt: 'تحويل برقي', ttDesc: '50% عربون 50% قبل الشحن', lc: 'اعتماد مستندي', lcDesc: 'لأوامر أكثر من 10 حاويات', paymentDetails: 'USD، EUR مقبولة', docs: 'وثائق التصدير', doc1: 'بوليصة الشحن', doc2: 'فاتورة تجارية', doc3: 'قائمة التعبئة', doc4: 'شهادة المنشأ', doc5: 'إعلان التصدير', doc6: 'MSDS', doc7: 'شهادة الجودة', moq: 'الحد الأدنى للطلب', moqDesc: 'أحجام مرنة', fcl: 'حاوية 20 قدم', lcl: '1 طن', fclDesc: '18-20 طن', lclDesc: 'أمر عينة', readyOrder: 'جاهز للطلب؟', contactSales: 'CONTACT المبيعات' },
    blog: { title: 'المدونة', subtitle: 'مقالات ومعلومات', cta: 'معلومات خبرية.', allPosts: 'جميع المقالات', noArticles: 'لا توجد مقالات بعد', checkBack: 'تحقق قريباً!', stayUpdated: 'ابق على اطلاع', stayUpdatedDesc: 'اشترك لنحصل على آخر المعلومات.', enterEmail: 'بريدك الإلكتروني', subscribing: 'جارٍ الاشتراك...', subscribe: 'اشترك', success: 'شكراً voor الاشتراك!', orContact: 'أو تواصل على واتساب', privacy: 'نحترم خصوصيتك.', readMore: 'اقرأ المزيد', minRead: 'دقيقة للقراءة' },
    keywords: ['فحم شيشة']
  },
  de: {
    nav: { home: 'Startseite', products: 'Produkte', shisha: 'Shisha Kohle', bbq: 'BBQ Kohle', oem: 'OEM', quality: 'Qualität', export: 'Export', about: 'Über uns', blog: 'Blog', contact: 'Kontakt' },
    hero: { title: 'Premium Kokosnuss-Kohle', subtitle: 'Von Indonesien', cta1: 'Produkte', cta2: 'Probe' },
    common: { learnMore: 'Mehr', getSample: 'Probe', contactUs: 'Kontakt', viewSpecs: 'Spezifikationen', freeSample: 'Probe', wholesale: 'Großhandel', factory: 'Fabrik', manufacturer: 'Hersteller', exporter: 'Exporteur', seeMore: 'Mehr' },
    footer: { description: 'Beste Fabrik.', products: 'Produkte', company: 'Unternehmen', getInTouch: 'Kontakt', shisha: 'Shisha', bbq: 'BBQ', oem: 'OEM', quality: 'Qualität', export: 'Export', about: 'Über uns', contact: 'Kontakt', allRights: 'Alle Rechte.' },
    products: { title: 'Produkte', subtitle: 'Premium.', shishaName: 'Shisha', shishaDesc: 'Premium.', bbqName: 'BBQ', bbqDesc: 'Hochhitze.', burnTime: 'Brenndauer', ashContent: 'Asche', noOdor: 'Geruchlos', heatValue: 'Heizwert', heroTitle: 'Premium Kokosnuss-Kohle', heroDesc: 'Hochwertige Kokosnusskohle.', shishaSub: 'Premium Shisha-Kohle', bbqSub: 'Premium Grillkohle', shishaFeature1: '2+ Stunden Brenndauer', shishaFeature2: 'Asche 1.6% - 2.5%', shishaFeature3: '650°C', shishaFeature4: 'Geruchlos', shishaFeature5: 'Verschiedene Formen', shishaFeature6: 'OEM unterstützt', bbqFeature1: 'Hohe Hitze', bbqFeature2: 'Langlebig', bbqFeature3: 'Wenig Asche', bbqFeature4: 'Natürlich', bbqFeature5: 'Leicht entzündbar', bbqFeature6: 'Umweltfreundlich', qualityGrades: 'Qualitätsstufen', qualityGradesDesc: 'Drei Stufen.', standard: 'Standard', standardDesc: 'Einstieg', premium: 'Premium', premiumDesc: 'Bestes Preis-Leistung', super: 'Super Premium', superDesc: 'Luxusqualität', popular: 'BELIEBT', burn2: '2+ Stunden', burn3: '2.5+ Stunden', burn4: '3+ Stunden', moisture1: 'Feuchtigkeit 6-8%', moisture2: 'Feuchtigkeit 5-7%', moisture3: 'Feuchtigkeit 4-6%', carbon1: 'Kohlenstoff 75%', carbon2: 'Kohlenstoff 78%', carbon3: 'Kohlenstoff 80%', oemTitle: 'OEM & Eigenmarke', oemDesc: 'Eigene Marke erstellen.', oem1: 'Vertraulichkeit & NDA', oem2: 'Verpackungsdesign', oem3: 'Verpackungsoptionen', ctaDesc: 'Kontaktieren Sie uns.' },
    about: { title: 'Über uns', subtitle: 'Fabrik', description: 'Führender Hersteller.', yearsExp: 'Erfahrung', tonsExported: 'Exportiert', countries: 'Länder', iso: 'ISO', halal: 'Halal', eco: 'Öko', labTested: 'Getestet', productionCapacity: 'Kapazität', exportCountries: 'Exporte', clients: 'Kunden', factoryTitle: 'Fabrik', factoryDesc: 'Modern.', modernEquip: 'Ausstattung', modernEquipDesc: 'Maschinen.', qcCert: 'Zertifiziert', qcCertDesc: 'ISO.', globalReady: 'Export', globalReadyDesc: 'International.', whyIndo: 'Warum?', richPotassium: 'Kalium', richPotassiumDesc: 'Reich.', highCarbon: 'Kohlenstoff', highCarbonDesc: '75-80%.', odorless: 'Geruchlos', odorlessDesc: 'Natürlich.', sustainable: 'Nachhaltig', sustainableDesc: 'Größter Produzent.', visitFactory: 'Besuchen', visitFactoryDesc: 'Willkommen.' },
    contact: { title: 'Kontakt', subtitle: 'Bestellen?', cta: 'Kontaktieren.', whatsapp: 'WhatsApp', email: 'admin@monocharcoal.com', yourName: 'Name', yourEmail: 'Email', yourMessage: 'Nachricht', send: 'Senden', openingEmail: 'Öffne...', getQuote: 'Angebot', readyOrder: 'Bereit?', factoryLocation: 'Standort', phone: 'Telefon', responseTime: 'Antwort', within24: '24 Stunden', sendMessage: 'Nachricht', formDesc: 'Antwort 24h.', company: 'Firma', country: 'Land', messagePlaceholder: 'Anforderungen', sending: 'Sende...', thankYou: 'Danke!', preferWA: 'WhatsApp?', WADesc: 'Schnell.', seoDesc: 'Kontaktieren.' },
    whyChoose: { title: 'Warum Mono', subtitle: 'Beste Kohle', problem: 'Indonesien beste.', butFinding: 'Schwierig zu finden.', description: 'Viele Probleme.', onTime: 'Pünktlich', onTimeDesc: 'Struktur.', docs: 'Dokumente', docsDesc: 'Vollständig.', logistics: 'Logistik', logisticsDesc: 'Ende zu Ende.', quality: 'Qualität', qualityDesc: 'Getestet.', downloadProfile: 'Profil' },
    pages: { about: 'Über uns', products: 'Produkte', oem: 'OEM', quality: 'Qualität', export: 'Export', blog: 'Blog', contact: 'Kontakt' },
    oem: { charcoalMfg: 'Herstellung', createBrand: 'Marke erstellen.', howItWorks: 'Wie es geht', requestQuote: 'Angebot', whyPartner: 'Warum wir?', confidential: 'Vertraulich', confidentialDesc: 'NDA.', design: 'Design', designDesc: 'Ihre Verpackung.', packaging: 'Verpackung', packagingDesc: 'Optionen.', docs: 'Dokumente', docsDesc: 'Export.', oemProcess: 'Prozess', inquiry: 'Anfrage', inquiryDesc: 'Anforderungen', sample: 'Muster', sampleDesc: 'Genehmigung', design2: 'Design', design2Desc: 'Verpackung', production: 'Produktion', productionDesc: 'Vollproduktion', shipping: 'Versand', shippingDesc: 'Weltweit', packagingOptions: 'Optionen', innerBox: 'Innenbox', masterBox: 'Masterbox', plastic: 'Plastik', sizes: 'Größen:', features: 'Features:', fullColor: 'Vollfarbe', lamination: 'Lamination', embossing: 'Embossing', colorPrint: 'Farbe', uv: 'UV', customSize: 'Sondergröße', heatSeal: 'Heat seal', zipLock: 'Zip', standPouch: 'Standbeutel', variousSizes: 'Verschiedene Größen', customPrint: 'Druck', brandSafe: 'Schutz', brandSafeDesc: 'NDA.', signedNDA: 'NDA', dedicatedLine: 'Linie', designConf: 'Design confidentiality', startBrand: 'Marke starten', startBrandDesc: 'Ihre Marke.', contactOEM: 'Kontakt' },
    quality: { title: 'Qualität & Zertifikate', subtitle: 'Qualität die Sie vertrauen', cta: 'QC-Prozess anzeigen', viewQC: 'QC-Prozess anzeigen', requestReports: 'Berichte anfordern', intCert: 'Internationale Zertifikate', iso: 'ISO 9001:2015', isoDesc: 'Qualitätsmanagementsystem', exportLic: 'Exportlizenz', exportLicDesc: 'Indonesische Regierung', factoryAudit: 'Werksaudit', factoryAuditDesc: 'Drittpartei verifiziert', msds: 'MSDS', msdsDesc: 'Sicherheitsdatenblatt', qcProcess: '8-Schritt-QC', qcProcessDesc: 'Konsistente Qualität', rawMaterial: 'Rohstoffprüfung', rawMaterialDesc: 'Kokosnüsse testen', carbonization: 'Carbonisierung', carbonizationDesc: 'Temperatur überwacht', grinding: 'Präzisionsmahlung', grindingDesc: 'Korrekte Netzgröße', mixing: 'Mischverhältnis', mixingDesc: 'Genaue Messung', pressing: 'Pressen & Formen', pressingDesc: 'Hydraulischer Druck', drying: 'Trocknen', dryingDesc: 'Kontrolliertes Trocknen', testing: 'Qualitätstest', testingDesc: 'Aschegehalt', finalInspect: 'Endkontrolle', finalInspectDesc: 'Sichtprüfung', labTesting: 'Labortests', labTestingDesc: 'Jede Charge getestet', ashContent: 'Aschegehalt', ashContentDesc: '1.6% - 2.5%', moisture: 'Feuchtigkeit', moistureDesc: '4% - 8%', fixedCarbon: 'Festkohlenstoff', fixedCarbonDesc: '75% - 80%', calorific: 'Heizwert', calorificDesc: '7,500 cal/g', thirdParty: 'Drittprüfung', thirdPartyDesc: 'SGS oder Intertek', thirdPartyCTA: 'Export-Info', reqDocs: 'Dokumente anfordern', reqDocsDesc: 'Berichte mit jeder Sendung' },
    export: { title: 'Export & Versand', subtitle: 'Globaler Versand', cta: 'Versandrouten', viewShipping: 'Versandrouten', getQuote: 'Angebot', country: 'Land', port: 'Hafen', transit: 'Transitzeit', containerType: 'Containertyp', capacity: 'Kapazität', dims: 'Abmessungen', prodTime: 'Produktion & Lieferzeit', prodTimeDesc: 'Standard-Lieferzeiten', loadingPort: 'Ladehäfen', loadingPortDesc: 'Jakarta, Semarang, Surabaya', payment: 'Zahlungsbedingungen', paymentDesc: 'Flexible Optionen', tt: 'Telegraph Transfer', ttDesc: '50% Voraus, 50% vor Versand', lc: 'Akkreditiv', lcDesc: 'Für über 10 Container', paymentDetails: 'USD, EUR akzeptiert', docs: 'Exportdokumente', doc1: 'Konnossement', doc2: 'Handelsrechnung', doc3: 'Packliste', doc4: 'Ursprungszeugnis', doc5: 'Exportdeklaration', doc6: 'MSDS', doc7: 'Qualitätszeugnis', moq: 'Mindestbestellmenge', moqDesc: 'Flexible Größen', fcl: '20ft Container', lcl: '1 Tonne', fclDesc: '18-20 Tonnen', lclDesc: 'Musterbestellung', readyOrder: 'Bereit?', contactSales: 'Vertrieb kontaktieren' },
    blog: { title: 'Blog', subtitle: 'Einblicke & Ratgeber', cta: 'Facheinblicke.', allPosts: 'Alle Beiträge', noArticles: 'Noch keine Artikel', checkBack: 'Bleiben Sie dran!', stayUpdated: 'Aktuell bleiben', stayUpdatedDesc: 'Für Einblicke anmelden.', enterEmail: 'Ihre Email', subscribing: 'Anmelden...', subscribe: 'Anmelden', success: 'Danke fürs Anmelden!', orContact: 'Oder WhatsApp', privacy: 'Wir respektieren Datenschutz.', readMore: 'Mehr lesen', minRead: 'Min. Lesezeit' },
    keywords: ['Shisha Kohle']
  },
  fr: {
    nav: { home: 'Accueil', products: 'Produits', shisha: 'Charbon Shisha', bbq: 'Charbon BBQ', oem: 'OEM', quality: 'Qualité', export: 'Export', about: 'À propos', blog: 'Blog', contact: 'Contact' },
    hero: { title: 'Charbon Premium', subtitle: "De l'Indonésie", cta1: 'Produits', cta2: 'Échantillon' },
    common: { learnMore: 'En Savoir Plus', getSample: 'Échantillon', contactUs: 'Contact', viewSpecs: 'Voir', freeSample: 'Échantillon', wholesale: 'Gros', factory: 'Usine', manufacturer: 'Fabricant', exporter: 'Exportateur', seeMore: 'Voir Plus' },
    footer: { description: 'Meilleure usine.', products: 'Produits', company: 'Entreprise', getInTouch: 'Contact', shisha: 'Shisha', bbq: 'BBQ', oem: 'OEM', quality: 'Qualité', export: 'Export', about: 'À propos', contact: 'Contact', allRights: 'Droits réservés.' },
    products: { title: 'Produits', subtitle: 'Premium.', shishaName: 'Shisha', shishaDesc: 'Premium.', bbqName: 'BBQ', bbqDesc: 'Haute chaleur.', burnTime: 'Durée', ashContent: 'Cendres', noOdor: 'Sans odeur', heatValue: 'Chaleur', heroTitle: 'Charbon Premium', heroDesc: 'Charbon de qualité.', shishaSub: 'Charbon shisha premium', bbqSub: 'Charbon BBQ premium', shishaFeature1: '2+ heures', shishaFeature2: 'Cendres 1.6% - 2.5%', shishaFeature3: '650°C', shishaFeature4: 'Sans odeur', shishaFeature5: 'Formes variées', shishaFeature6: 'OEM supporté', bbqFeature1: 'Haute chaleur', bbqFeature2: 'Longue durée', bbqFeature3: 'Peu de cendres', bbqFeature4: 'Naturel', bbqFeature5: 'Allumage facile', bbqFeature6: 'Écologique', qualityGrades: 'Qualités', qualityGradesDesc: 'Trois niveaux.', standard: 'Standard', standardDesc: 'Entrée', premium: 'Premium', premiumDesc: 'Meilleur rapport', super: 'Super Premium', superDesc: 'Luxe', popular: 'POPULAIRE', burn2: '2+ heures', burn3: '2.5+ heures', burn4: '3+ heures', moisture1: 'Humidité 6-8%', moisture2: 'Humidité 5-7%', moisture3: 'Humidité 4-6%', carbon1: 'Carbone 75%', carbon2: 'Carbone 78%', carbon3: 'Carbone 80%', oemTitle: 'OEM & Marque Privée', oemDesc: 'Créez votre marque.', oem1: 'Confidentialité & NDA', oem2: 'Design packaging', oem3: 'Options packaging', ctaDesc: 'Contactez-nous.' },
    about: { title: 'À propos', subtitle: 'Usine Indonesia', description: 'Leader.', yearsExp: 'Années', tonsExported: 'Tonnes', countries: 'Pays', iso: 'ISO', halal: 'Halal', eco: 'Éco', labTested: 'Testé', productionCapacity: 'Capacité', exportCountries: 'Export', clients: 'Clients', factoryTitle: 'Usine', factoryDesc: 'Moderne.', modernEquip: 'Équipement', modernEquipDesc: 'Machines.', qcCert: 'Certifié', qcCertDesc: 'ISO.', globalReady: 'Export', globalReadyDesc: 'International.', whyIndo: 'Pourquoi?', richPotassium: 'Potassium', richPotassiumDesc: 'Riche.', highCarbon: 'Carbone', highCarbonDesc: '75-80%.', odorless: 'Sans odeur', odorlessDesc: 'Naturel.', sustainable: 'Durable', sustainableDesc: 'Plus grand.', visitFactory: 'Visiter', visitFactoryDesc: 'Bienvenue.' },
    contact: { title: 'Contact', subtitle: 'Commander?', cta: 'Contactez.', whatsapp: 'WhatsApp', email: 'admin@monocharcoal.com', yourName: 'Nom', yourEmail: 'Email', yourMessage: 'Message', send: 'Envoyer', openingEmail: 'Ouverture...', getQuote: 'Devis', readyOrder: 'Prêt?', factoryLocation: 'Emplacement', phone: 'Téléphone', responseTime: 'Réponse', within24: '24 heures', sendMessage: 'Envoyer', formDesc: 'Réponse 24h.', company: 'Entreprise', country: 'Pays', messagePlaceholder: 'Besoins', sending: 'Envoi...', thankYou: 'Merci!', preferWA: 'WhatsApp?', WADesc: 'Rapide.', seoDesc: 'Contactez-nous.' },
    whyChoose: { title: 'Pourquoi Mono', subtitle: 'Meilleur charbon', problem: 'Indonesia meilleur.', butFinding: 'Difficile.', description: 'Problèmes.', onTime: 'À temps', onTimeDesc: 'Processus.', docs: 'Docs', docsDesc: 'Complets.', logistics: 'Logistique', logisticsDesc: 'Complet.', quality: 'Qualité', qualityDesc: 'Testé.', downloadProfile: 'Télécharger' },
    pages: { about: 'À propos', products: 'Produits', oem: 'OEM', quality: 'Qualité', export: 'Export', blog: 'Blog', contact: 'Contact' },
    oem: { charcoalMfg: 'Fabrication', createBrand: 'Créez votre marque.', howItWorks: 'Comment', requestQuote: 'Devis', whyPartner: 'Pourquoi?', confidential: 'Confidentialité', confidentialDesc: 'NDA.', design: 'Design', designDesc: 'Votre packaging.', packaging: 'Packaging', packagingDesc: 'Options.', docs: 'Docs', docsDesc: 'Export.', oemProcess: 'Processus', inquiry: 'Demande', inquiryDesc: 'Exigences', sample: 'Échantillon', sampleDesc: 'Approbation', design2: 'Design', design2Desc: 'Packaging', production: 'Production', productionDesc: 'Production totale', shipping: 'Expédition', shippingDesc: 'Mondiale', packagingOptions: 'Options', innerBox: 'Boîte interne', masterBox: 'Boîte maître', plastic: 'Plastique', sizes: 'Tailles:', features: 'Features:', fullColor: 'Couleur complète', lamination: 'Lamination', embossing: 'Embossage', colorPrint: 'Couleur', uv: 'UV', customSize: 'Taille-custom', heatSeal: 'Scellé', zipLock: 'Zip', standPouch: 'Sac debout', variousSizes: 'Tailles variées', customPrint: 'Impression custom', brandSafe: 'Protection', brandSafeDesc: 'NDA.', signedNDA: 'NDA', dedicatedLine: 'Ligne', designConf: 'Confidentialité', startBrand: 'Démarrer', startBrandDesc: 'Votre marque.', contactOEM: 'Contact' },
    quality: { title: 'Qualité & Certifications', subtitle: 'Qualité уверен', cta: 'Voir processus QC', viewQC: 'Voir processus QC', requestReports: 'Demander rapports', intCert: 'Certifications internationales', iso: 'ISO 9001:2015', isoDesc: 'Système de management', exportLic: 'Licence экспорт', exportLicDesc: 'Gouvernement indonésien', factoryAudit: 'Audit usine', factoryAuditDesc: 'Vérifié tierce partie', msds: 'MSDS', msdsDesc: 'Fiche sécurité', qcProcess: '8 étapes QC', qcProcessDesc: 'Qualité cohérente', rawMaterial: 'Contrôle matières', rawMaterialDesc: 'Test coques', carbonization: 'Carbonisation', carbonizationDesc: 'Température contrôlée', grinding: 'Broyage précis', grindingDesc: 'Taille mesh correcte', mixing: 'Mélange', mixingDesc: 'Mesures précises', pressing: 'Pressage', pressingDesc: 'Pression hydraulique', drying: 'Séchage', dryingDesc: 'Séchage contrôlé', testing: 'Test qualité', testingDesc: 'Teneur cendres', finalInspect: 'Inspection finale', finalInspectDesc: 'Contrôle visuel', labTesting: 'Tests laboratoire', labTestingDesc: 'Chaque lot testé', ashContent: 'Cendres', ashContentDesc: '1.6% - 2.5%', moisture: 'Humidité', moistureDesc: '4% - 8%', fixedCarbon: 'Carbone fixe', fixedCarbonDesc: '75% - 80%', calorific: 'Pouvoir calorifique', calorificDesc: '7,500 cal/g', thirdParty: 'Inspection tierce', thirdPartyDesc: 'SGS ou Intertek', thirdPartyCTA: 'Info экспорт', reqDocs: 'Demander docs', reqDocsDesc: 'Rapports avec chaque expédition' },
    export: { title: 'Export & Expédition', subtitle: 'Livraison mondiale', cta: 'Voir routes', viewShipping: 'Voir routes', getQuote: 'Devis', country: 'Pays', port: 'Port', transit: 'Transit', containerType: 'Type conteneur', capacity: 'Capacité', dims: 'Dimensions', prodTime: 'Production & livraison', prodTimeDesc: 'Délais standards', loadingPort: 'Ports de chargement', loadingPortDesc: 'Jakarta, Semarang, Surabaya', payment: 'Conditions paiement', paymentDesc: 'Options flexibles', tt: 'Virement', ttDesc: '50% avancer 50% avant', lc: 'Crédit documentaire', lcDesc: 'Pour plus 10 conteneurs', paymentDetails: 'USD EUR acceptés', docs: 'Documents export', doc1: 'Connaissement', doc2: 'Facture commerciale', doc3: 'Liste colisage', doc4: 'Certificat origine', doc5: 'Déclaration export', doc6: 'MSDS', doc7: 'Certificat qualité', moq: 'Quantité minimum', moqDesc: 'Tailles flexibles', fcl: 'Conteneur 20pieds', lcl: '1 tonne', fclDesc: '18-20 tonnes', lclDesc: 'Commande échantillon', readyOrder: 'Prêt?', contactSales: 'Contacter ventes' },
    blog: { title: 'Blog', subtitle: 'Avis & Guides', cta: 'Avis expertise.', allPosts: 'Tous articles', noArticles: 'Pas encore', checkBack: 'Revenez bientôt!', stayUpdated: 'Stay updated', stayUpdatedDesc: 'Abonnez-vous.', enterEmail: 'Votre email', subscribing: 'Abonnement...', subscribe: 'Abonner', success: 'Merci!', orContact: 'Ou WhatsApp', privacy: 'Respect vie privée.', readMore: 'Lire plus', minRead: 'min lecture' },
    keywords: ['charbon shisha']
  },
  tr: {
    nav: { home: 'Ana Sayfa', products: 'Ürünler', shisha: 'Nargate', bbq: 'Izgara', oem: 'OEM', quality: 'Kalite', export: 'İhracat', about: 'Hakkımızda', blog: 'Blog', contact: 'İletişim' },
    hero: { title: 'Premium', subtitle: 'Indonesya', cta1: 'Ürünler', cta2: 'Numune' },
    common: { learnMore: 'Daha Fazla', getSample: 'Numune', contactUs: 'İletişim', viewSpecs: 'Özellikler', freeSample: 'Numune', wholesale: 'Toptan', factory: 'Fabrika', manufacturer: 'Üretici', exporter: 'İhracatçı', seeMore: 'Daha Fazla' },
    footer: { description: 'En iyi fabrika.', products: 'Ürünler', company: 'Şirket', getInTouch: 'İletişim', shisha: 'Nargate', bbq: 'Izgara', oem: 'OEM', quality: 'Kalite', export: 'İhracat', about: 'Hakkımızda', contact: 'İletişim', allRights: 'Tüm hakları.' },
    products: { title: 'Ürünler', subtitle: 'Premium.', shishaName: 'Nargate', shishaDesc: 'Premium.', bbqName: 'Izgara', bbqDesc: 'Yüksek ısı.', burnTime: 'Yanma', ashContent: 'Kül', noOdor: 'Kokusuz', heatValue: 'Isı', heroTitle: 'Premium Kömür', heroDesc: 'Yüksek kalite kömür.', shishaSub: 'Premium nargate kömürü', bbqSub: 'Premium ızgara kömürü', shishaFeature1: '2+ saat yanma', shishaFeature2: 'Kül %1.6 - 2.5', shishaFeature3: '650°C', shishaFeature4: 'Kokusuz', shishaFeature5: 'Çeşitli şekiller', shishaFeature6: 'OEM destekli', bbqFeature1: 'Yüksek ısı', bbqFeature2: 'Uzun süreli', bbqFeature3: 'Az kül', bbqFeature4: 'Doğal', bbqFeature5: 'Kolay tutuşma', bbqFeature6: 'Çevre dostu', qualityGrades: 'Kalite Dereceleri', qualityGradesDesc: 'Üç seviye.', standard: 'Standart', standardDesc: 'Giriş seviye', premium: 'Premium', premiumDesc: 'En iyi değer', super: 'Süper Premium', superDesc: 'Lüks kalite', popular: 'POPÜLER', burn2: '2+ saat', burn3: '2.5+ saat', burn4: '3+ saat', moisture1: 'Nem %6-8', moisture2: 'Nem %5-7', moisture3: 'Nem %4-6', carbon1: 'Karbon %75', carbon2: 'Karbon %78', carbon3: 'Karbon %80', oemTitle: 'OEM & Özel Marka', oemDesc: 'Markanızı oluşturun.', oem1: 'Gizlilik & NDA', oem2: 'Ambalaj tasarımı', oem3: 'Ambalaj seçenekleri', ctaDesc: 'Bize ulaşın.' },
    about: { title: 'Hakkımızda', subtitle: 'Fabrika', description: 'Lider üretici.', yearsExp: 'Yıl', tonsExported: 'Ton', countries: 'Ülke', iso: 'ISO', halal: 'Helal', eco: 'Eco', labTested: 'Test', productionCapacity: 'Kapasite', exportCountries: 'İhracat', clients: 'Müşteriler', factoryTitle: 'Fabrika', factoryDesc: 'Modern.', modernEquip: 'Ekipman', modernEquipDesc: 'Makineler.', qcCert: 'Sertifikalı', qcCertDesc: 'ISO.', globalReady: 'İhracat', globalReadyDesc: 'Uluslararası.', whyIndo: 'Neden?', richPotassium: 'Potasyum', richPotassiumDesc: 'Zengin.', highCarbon: 'Karbon', highCarbonDesc: '75-80%.', odorless: 'Kokusuz', odorlessDesc: 'Doğal.', sustainable: 'Sürdürülebilir', sustainableDesc: 'En büyük.', visitFactory: 'Ziyaret', visitFactoryDesc: 'Hoş geldiniz.' },
    contact: { title: 'İletişim', subtitle: 'Sipariş?', cta: 'İletişime geç.', whatsapp: 'WhatsApp', email: 'admin@monocharcoal.com', yourName: 'Ad', yourEmail: 'Email', yourMessage: 'Mesaj', send: 'Gönder', openingEmail: 'Açılıyor...', getQuote: 'Teklif', readyOrder: 'Hazır?', factoryLocation: 'Konum', phone: 'Telefon', responseTime: 'Yanıt', within24: '24 saat', sendMessage: 'Mesaj gönder', formDesc: '24 saat.', company: 'Şirket', country: 'Ülke', messagePlaceholder: 'İhtiyaçlar', sending: 'Gönderiliyor...', thankYou: 'Teşekkürler!', preferWA: 'WhatsApp?', WADesc: 'Hızlı.', seoDesc: 'İletişime geç.' },
    whyChoose: { title: 'Neden Mono', subtitle: 'En iyi', problem: 'En iyi.', butFinding: 'Zor.', description: 'Sorunlar.', onTime: 'Zamanında', onTimeDesc: 'Süreç.', docs: 'Belgeler', docsDesc: 'Tam.', logistics: 'Lojistik', logisticsDesc: 'Tam.', quality: 'Kalite', qualityDesc: 'Test.', downloadProfile: 'İndir' },
    pages: { about: 'Hakkımızda', products: 'Ürünler', oem: 'OEM', quality: 'Kalite', export: 'İhracat', blog: 'Blog', contact: 'İletişim' },
    oem: { charcoalMfg: 'Üretim', createBrand: 'Marka oluştur.', howItWorks: 'Nasıl', requestQuote: 'Teklif', whyPartner: 'Neden?', confidential: 'Gizlilik', confidentialDesc: 'NDA.', design: 'Tasarım', designDesc: 'Paketiniz.', packaging: 'Paketleme', packagingDesc: 'Seçenekler.', docs: 'Belgeler', docsDesc: 'İhracat.', oemProcess: 'Süreç', inquiry: 'Sorgu', inquiryDesc: 'Gereksinimler', sample: 'Numune', sampleDesc: 'Onay', design2: 'Tasarım', design2Desc: 'Paketleme', production: 'Üretim', productionDesc: 'Tam üretim', shipping: 'Kargo', shippingDesc: 'Dünya geneli', packagingOptions: 'Seçenekler', innerBox: 'İç kutu', masterBox: 'Ana kutu', plastic: 'Plastik', sizes: 'Boyutlar:', features: 'Özellikler:', fullColor: 'Tam renk', lamination: 'Laminasyon', embossing: 'Kabartma', colorPrint: 'Renk', uv: 'UV', customSize: 'Özel boyut', heatSeal: 'Isı mühürleme', zipLock: 'Zip', standPouch: 'Duran poşet', variousSizes: 'Çeşitli boyutlar', customPrint: 'Özel baskı', brandSafe: 'Güvenli', brandSafeDesc: 'NDA.', signedNDA: 'NDA', dedicatedLine: 'Hat', designConf: 'Tasarım gizliliği', startBrand: 'Başla', startBrandDesc: 'Markanızı.', contactOEM: 'İletişim' },
    quality: { title: 'Kalite & Sertifikalar', subtitle: 'Güvendiğiniz kalite', cta: 'QC Sürecini gör', viewQC: 'QC Sürecini gör', requestReports: 'Rapor iste', intCert: 'Uluslararası Sertifikalar', iso: 'ISO 9001:2015', isoDesc: 'Kalite Yönetim Sistemi', exportLic: 'İhracat Lisansı', exportLicDesc: 'Endonezya Hükümeti', factoryAudit: 'Fabrika Denetimi', factoryAuditDesc: '3. Tarafça Doğrulanan', msds: 'MSDS', msdsDesc: 'Güvenlik Bilgi Formu', qcProcess: '8 Adım QC', qcProcessDesc: 'Tutarlı kalite', rawMaterial: 'Hammadde Kontrolü', rawMaterialDesc: 'Kabuğu testi', carbonization: 'Karbonizasyon', carbonizationDesc: 'Sıcaklık izleniyor', grinding: 'Öğütme Hassasiyetı', grindingDesc: 'Doğru mesh boyutu', mixing: 'Karışım Oranı', mixingDesc: 'Doğru ölçüm', pressing: 'Presleme', pressingDesc: 'Hidrolik basınç', drying: 'Kurutma', dryingDesc: 'Kontrollü kurutma', testing: 'Kalite Testi', testingDesc: 'Kül içeriği', finalInspect: 'Son Kontrol', finalInspectDesc: 'Görsel kontrol', labTesting: 'Laboratuvar Testleri', labTestingDesc: 'Her parti test edilir', ashContent: 'Kül İçeriği', ashContentDesc: '1.6% - 2.5%', moisture: 'Nem', moistureDesc: '4% - 8%', fixedCarbon: 'Sabit Karbon', fixedCarbonDesc: '75% - 80%', calorific: 'Kalorifik Değer', calorificDesc: '7,500 kal/g', thirdParty: '3. Taraf İnceleme', thirdPartyDesc: 'SGS veya Intertek', thirdPartyCTA: 'İhracat Bilgileri', reqDocs: 'Döküman iste', reqDocsDesc: 'Her sevkıyatta raporlar' },
    export: { title: 'İhracat & Nakliye', subtitle: 'Küresel Nakliye', cta: 'Rotaları gör', viewShipping: 'Rotaları gör', getQuote: 'Teklif al', country: 'Ülke', port: 'Liman', transit: 'Transit süresi', containerType: 'Konteyner Tipi', capacity: 'Kapasite', dims: 'Boyutlar', prodTime: 'Üretim & Teslim', prodTimeDesc: 'Standart süreler', loadingPort: 'Yükleme Limanları', loadingPortDesc: 'Jakarta, Semarang, Surabaya', payment: 'Ödeme Koşulları', paymentDesc: 'Esnek seçenekler', tt: 'Telegraph Transfer', ttDesc: '%50 peşin %50 önce', lc: 'Akreditif', lcDesc: '10+ konteyner için', paymentDetails: 'USD EUR kabul', docs: 'İhracat Belgeleri', doc1: 'Konşimento', doc2: 'Ticari Fatura', doc3: 'Paket Listesi', doc4: 'Menşe Şahadetnamesi', doc5: 'İhracat Beyanı', doc6: 'MSDS', doc7: 'Kalite Sertifikası', moq: 'Minimum Sipariş', moqDesc: 'Esnek boyutlar', fcl: '20ft Konteyner', lcl: '1 ton', fclDesc: '18-20 ton', lclDesc: 'Numune sipariş', readyOrder: 'Hazır mı?', contactSales: 'Satışla iletişim' },
    blog: { title: 'Blog', subtitle: 'İçgörüler & Rehberler', cta: 'Uzman içgörüleri.', allPosts: 'Tüm yazılar', noArticles: 'Henüz yazı yok', checkBack: 'Yakında kontrol et!', stayUpdated: 'Güncel kal', stayUpdatedDesc: 'Abone olun.', enterEmail: 'Email', subscribing: 'Abone olunuyor...', subscribe: 'Abone ol', success: 'Teşekkürler!', orContact: 'Veya WhatsApp', privacy: 'Gizliliğe saygı.', readMore: 'Devamını oku', minRead: 'dk okuma' },
    keywords: ['nargate kömürü']
  },
  ru: {
    nav: { home: 'Главная', products: 'Продукты', shisha: 'Кальян', bbq: 'Гриль', oem: 'OEM', quality: 'Качество', export: 'Экспорт', about: 'О нас', blog: 'Блог', contact: 'Контакты' },
    hero: { title: 'Премиум', subtitle: 'Из Индонезии', cta1: 'Продукты', cta2: 'Образец' },
    common: { learnMore: 'Подробнее', getSample: 'Образец', contactUs: 'Контакт', viewSpecs: 'Характеристики', freeSample: 'Образец', wholesale: 'Оптом', factory: 'Фабрика', manufacturer: 'Производитель', exporter: 'Экспортёр', seeMore: 'Подробнее' },
    footer: { description: 'Лучшая фабрика.', products: 'Продукты', company: 'Компания', getInTouch: 'Контакт', shisha: 'Кальян', bbq: 'Гр��ль', oem: 'OEM', quality: 'Качество', export: 'Экспорт', about: 'О нас', contact: 'Контакт', allRights: 'Все права.' },
    products: { title: 'Продукты', subtitle: 'Премиум.', shishaName: 'Кальян', shishaDesc: 'Премиум.', bbqName: 'Гриль', bbqDesc: 'Высококалорийный.', burnTime: 'Горение', ashContent: 'Зола', noOdor: 'Без запаха', heatValue: 'Теплота', heroTitle: 'Премиум уголь', heroDesc: 'Высококачественный уголь.', shishaSub: 'Премиум кальянный уголь', bbqSub: 'Премиум уголь для гриля', shishaFeature1: '2+ часа горения', shishaFeature2: 'Зола 1.6% - 2.5%', shishaFeature3: '650°C', shishaFeature4: 'Без запаха', shishaFeature5: 'Различные формы', shishaFeature6: 'OEM поддержка', bbqFeature1: 'Высокая теплота', bbqFeature2: 'Долгое горение', bbqFeature3: 'Мало золы', bbqFeature4: 'Натуральный', bbqFeature5: 'Лёгкий розжиг', bbqFeature6: 'Экологичный', qualityGrades: 'Степени качества', qualityGradesDesc: 'Три уровня.', standard: 'Стандарт', standardDesc: 'Начальный', premium: 'Премиум', premiumDesc: 'Лучшее соотношение', super: 'Супер Премиум', superDesc: 'Люксовое качество', popular: 'ПОПУЛЯРНЫЙ', burn2: '2+ часа', burn3: '2.5+ часа', burn4: '3+ часа', moisture1: 'Влажность 6-8%', moisture2: 'Влажность 5-7%', moisture3: 'Влажность 4-6%', carbon1: 'Углерод 75%', carbon2: 'Углерод 78%', carbon3: 'Углерод 80%', oemTitle: 'OEM & Частная марка', oemDesc: 'Создайте свой бренд.', oem1: 'Конфиденциальность & NDA', oem2: 'Дизайн упаковки', oem3: 'Варианты упаковки', ctaDesc: 'Свяжитесь с нами.' },
    about: { title: 'О нас', subtitle: 'Фабрика', description: 'Лидер.', yearsExp: 'Лет', tonsExported: 'Тонн', countries: 'Стран', iso: 'ISO', halal: 'Халяль', eco: 'Эко', labTested: 'Тест', productionCapacity: 'Мощность', exportCountries: 'Экспорт', clients: 'Клиенты', factoryTitle: 'Фабрика', factoryDesc: 'Современная.', modernEquip: 'Оборудование', modernEquipDesc: 'Машины.', qcCert: 'Сертификат', qcCertDesc: 'ISO.', globalReady: 'Экспорт', globalReadyDesc: 'Международный.', whyIndo: 'Почему?', richPotassium: 'Калий', richPotassiumDesc: 'Богатый.', highCarbon: 'Углерод', highCarbonDesc: '75-80%.', odorless: 'Без запаха', odorlessDesc: 'Натуральный.', sustainable: 'Устойчивое', sustainableDesc: 'Крупнейший.', visitFactory: 'Посетить', visitFactoryDesc: 'Добро пожаловать.' },
    contact: { title: 'Контакты', subtitle: 'Заказать?', cta: 'Свяжитесь.', whatsapp: 'WhatsApp', email: 'admin@monocharcoal.com', yourName: 'Имя', yourEmail: 'Email', yourMessage: 'Сообщение', send: 'Отправить', openingEmail: 'Открытие...', getQuote: 'КП', readyOrder: 'Готовы?', factoryLocation: 'Расположение', phone: 'Телефон', responseTime: 'Ответ', within24: '24 часа', sendMessage: 'Сообщение', formDesc: 'Ответ 24ч.', company: 'Компания', country: 'Страна', messagePlaceholder: 'Требования', sending: 'Отправка...', thankYou: 'Спасибо!', preferWA: 'WhatsApp?', WADesc: 'Быстрый.', seoDesc: 'Свяжитесь.' },
    whyChoose: { title: 'Почему Mono', subtitle: 'Лучший уголь', problem: 'Лучший.', butFinding: 'Сложно.', description: 'Проблемы.', onTime: 'В срок', onTimeDesc: 'Процесс.', docs: 'Документы', docsDesc: 'Полные.', logistics: 'Логистика', logisticsDesc: 'Полная.', quality: 'Качество', qualityDesc: 'Тест.', downloadProfile: 'Скачать' },
    pages: { about: 'О нас', products: 'Продукты', oem: 'OEM', quality: 'Качество', export: 'Экспорт', blog: 'Блог', contact: 'Контакты' },
    oem: { charcoalMfg: 'Производство', createBrand: 'Создайте бренд.', howItWorks: 'Как', requestQuote: 'КП', whyPartner: 'Почему?', confidential: 'Конфиденциальность', confidentialDesc: 'NDA.', design: 'Дизайн', designDesc: 'Ваша упаковка.', packaging: 'Упаковка', packagingDesc: 'Варианты.', docs: 'Документы', docsDesc: 'Экспорт.', oemProcess: 'Процесс', inquiry: 'Запрос', inquiryDesc: 'Требования', sample: 'Образец', sampleDesc: 'Согласование', design2: 'Дизайн', design2Desc: 'Упаковка', production: 'Производство', productionDesc: 'Полное', shipping: 'Доставка', shippingDesc: 'Мировая', packagingOptions: 'Варианты', innerBox: 'Внутренняя коробка', masterBox: 'Мастер коробка', plastic: 'Пластик', sizes: 'Размеры:', features: 'Особенности:', fullColor: 'Полный цвет', lamination: 'Ламинирование', embossing: 'Тиснение', colorPrint: 'Цветная печать', uv: 'УФ', customSize: 'Нестандартный', heatSeal: 'Термосварка', zipLock: 'Zip', standPouch: 'Стойка', variousSizes: 'Разные размеры', customPrint: 'Печать', brandSafe: 'Защита', brandSafeDesc: 'NDA.', signedNDA: 'NDA', dedicatedLine: 'Линия', designConf: 'Конфиденциальность', startBrand: 'Начать', startBrandDesc: 'Ваш бренд.', contactOEM: 'Контакт' },
    quality: { title: 'Качество & Сертификаты', subtitle: 'Качество которому доверяют', cta: 'Процесс QC', viewQC: 'Процесс QC', requestReports: 'Запросить отчёты', intCert: 'Международные сертификаты', iso: 'ISO 9001:2015', isoDesc: 'Система управления', exportLic: 'Экспорт лицензия', exportLicDesc: 'Индонезийское правительство', factoryAudit: 'Ауди�� завода', factoryAuditDesc: 'Подтверждено 3-й стороной', msds: 'MSDS', msdsDesc: 'Паспорт безопасности', qcProcess: '8-шаговый QC', qcProcessDesc: 'Последовательное качество', rawMaterial: 'Контроль сырья', rawMaterialDesc: 'Тестирование скорлупы', carbonization: 'Карбонизация', carbonizationDesc: 'Контроль температуры', grinding: 'Измельчение', grindingDesc: 'Правильный размер', mixing: 'Смешивание', mixingDesc: 'Точные измерения', pressing: 'Прессование', pressingDesc: 'Гидравлическое давление', drying: 'Сушка', dryingDesc: 'Контролируемая сушка', testing: 'Тестирование', testingDesc: 'Содержание золы', finalInspect: 'Финальный осмотр', finalInspectDesc: 'Визуальный осмотр', labTesting: 'Лабораторные тесты', labTestingDesc: 'Каждая партия тестируется', ashContent: 'Содержание золы', ashContentDesc: '1.6% - 2.5%', moisture: 'Влажность', moistureDesc: '4% - 8%', fixedCarbon: '固定 углерод', fixedCarbonDesc: '75% - 80%', calorific: 'Теплотворность', calorificDesc: '7,500 кал/г', thirdParty: '3-я сторона', thirdPartyDesc: 'SGS или Intertek', thirdPartyCTA: 'Инфо об экспорте', reqDocs: 'Запросить документы', reqDocsDesc: 'Отчёты с каждой отправкой' },
    export: { title: 'Экспорт & Доставка', subtitle: 'Глобальная доставка', cta: 'Маршруты доставки', viewShipping: 'Маршруты доставки', getQuote: 'Получить КП', country: 'Страна', port: 'Порт', transit: 'Транзит', containerType: 'Тип контейнера', capacity: 'Вместимость', dims: 'Размеры', prodTime: 'Производство и доставка', prodTimeDesc: 'Стандартные сроки', loadingPort: 'Погрузочные порты', loadingPortDesc: 'Джакарта, Семаранг, Сурабая', payment: 'Условия оплаты', paymentDesc: 'Гибкие варианты', tt: 'Телегр. перевод', ttDesc: '50% аванс 50% до отправки', lc: 'Аккредитив', lcDesc: 'Для заказов от 10 контейнеров', paymentDetails: 'USD, EUR принимаются', docs: 'Документы на экспорт', doc1: 'Коносамент', doc2: 'Коммерческий счёт', doc3: 'Упаковочный лист', doc4: 'Сертификат происхождения', doc5: 'Экспорт декларация', doc6: 'MSDS', doc7: 'Сертификат качества', moq: 'Минимальный заказ', moqDesc: 'Гибкие объёмы', fcl: 'Контейнер 20 футов', lcl: '1 тонна', fclDesc: '18-20 тонн', lclDesc: 'Образец заказа', readyOrder: 'Готовы заказать?', contactSales: 'Связаться с продажами' },
    blog: { title: 'Блог', subtitle: 'Статьи и руководства', cta: 'Экспертные статьи.', allPosts: 'Все статьи', noArticles: 'Пока нет статей', checkBack: 'Скоро проверьте!', stayUpdated: 'Будьте в курсе', stayUpdatedDesc: 'Подпишитесь на обновления.', enterEmail: 'Ваш email', subscribing: 'Подписка...', subscribe: 'Подписаться', success: 'Спасибо за подписку!', orContact: 'Или WhatsApp', privacy: 'Мы уважаем приватность.', readMore: 'Читать далее', minRead: 'мин чтения' },
    keywords: ['уголь для кальяна']
  },
  ja: {
    nav: { home: 'ホーム', products: '製品', shisha: 'シーシャ', bbq: 'BBQ', oem: 'OEM', quality: '品質', export: '輸出', about: '会社概要', blog: 'ブログ', contact: 'お問い合わせ' },
    hero: { title: 'プレミアム', subtitle: 'インドネシアから', cta1: '製品', cta2: 'サンプル' },
    common: { learnMore: '詳細', getSample: 'サンプル', contactUs: 'お問い合わせ', viewSpecs: '仕様', freeSample: 'サンプル', wholesale: '卸売', factory: '工場', manufacturer: 'メーカー', exporter: '輸出者', seeMore: 'もっと見る' },
    footer: { description: '最好的工場', products: '製品', company: '会社', getInTouch: 'お問い合わせ', shisha: 'シーシャ', bbq: 'BBQ', oem: 'OEM', quality: '品質', export: '輸出', about: '会社概要', contact: 'お問い合わせ', allRights: '著作権' },
    products: { title: '製品', subtitle: 'プレミアム', shishaName: 'シーシャ', shishaDesc: 'プレミアム', bbqName: 'BBQ', bbqDesc: '高火力', burnTime: '燃焼', ashContent: '灰分', noOdor: '無臭', heatValue: '熱量', heroTitle: 'プレミアム炭', heroDesc: '高品質ココナッツ炭.', shishaSub: 'プレミアムシーシャ炭', bbqSub: 'プレミアムBBQ炭', shishaFeature1: '2時間以上燃焼', shishaFeature2: '灰分1.6% - 2.5%', shishaFeature3: '650°C', shishaFeature4: '無臭', shishaFeature5: '複数の形状', shishaFeature6: 'OEM対応', bbqFeature1: '高熱量', bbqFeature2: '長時間燃焼', bbqFeature3: '少ない灰', bbqFeature4: '天然', bbqFeature5: '簡単着火', bbqFeature6: 'エコ', qualityGrades: '品質グレード', qualityGradesDesc: '3段階.', standard: 'スタンダード', standardDesc: 'エントリー', premium: 'プレミアム', premiumDesc: '最高コスパ', super: 'スーパープレミアム', superDesc: '最高品質', popular: '人気', burn2: '2時間以上', burn3: '2.5時間以上', burn4: '3時間以上', moisture1: '水分6-8%', moisture2: '水分5-7%', moisture3: '水分4-6%', carbon1: '炭素75%', carbon2: '炭素78%', carbon3: '炭素80%', oemTitle: 'OEM & プライベートラベル', oemDesc: '自社ブランドを作成.', oem1: '秘密保持 & NDA', oem2: 'パッケージデザイン', oem3: 'パッケージオプション', ctaDesc: 'お問い合わせください.' },
    about: { title: '会社概要', subtitle: '工場', description: 'リーディングメーカー', yearsExp: '年数', tonsExported: 'トン', countries: '国', iso: 'ISO', halal: 'ハラール', eco: 'エコ', labTested: 'テスト', productionCapacity: '能力', exportCountries: '輸出', clients: '顾客', factoryTitle: '工場', factoryDesc: '最新.', modernEquip: '設備', modernEquipDesc: '機械.', qcCert: '認証', qcCertDesc: 'ISO.', globalReady: '輸出可能', globalReadyDesc: '国際.', whyIndo: 'なぜ?', richPotassium: 'カリウム', richPotassiumDesc: '豊富.', highCarbon: '炭素', highCarbonDesc: '75-80%.', odorless: '無臭', odorlessDesc: '天然.', sustainable: '持続可能', sustainableDesc: '最大.', visitFactory: '見学', visitFactoryDesc: 'ようこそ.' },
    contact: { title: 'お問い合わせ', subtitle: '注文?', cta: 'お問い合わせ.', whatsapp: 'WhatsApp', email: 'admin@monocharcoal.com', yourName: 'お名前', yourEmail: 'メール', yourMessage: 'メッセージ', send: '送信', openingEmail: '開く...', getQuote: '見積もり', readyOrder: '準備OK?', factoryLocation: '場所', phone: '電話番号', responseTime: '応答', within24: '24時間', sendMessage: '送信', formDesc: '24時間以内.', company: '会社名', country: '国', messagePlaceholder: 'ご要望', sending: '送信中...', thankYou: 'ありがとう!', preferWA: 'WhatsApp?', WADesc: '早い.', seoDesc: 'お問い合わせ.' },
    whyChoose: { title: 'なぜMono', subtitle: '最高', problem: '印尼最好', butFinding: '難しい.', description: '問題.', onTime: '定時', onTimeDesc: '工程.', docs: '書類', docsDesc: '完整的.', logistics: '物流', logisticsDesc: 'エンドツーエンド.', quality: '品質', qualityDesc: 'テスト.', downloadProfile: 'ダウンロード' },
    pages: { about: '会社概要', products: '製品', oem: 'OEM', quality: '品質', export: '輸出', blog: 'ブログ', contact: 'お問い合わせ' },
    oem: { charcoalMfg: '製造', createBrand: 'ブランド作成', howItWorks: 'フロー', requestQuote: '見積もり', whyPartner: 'なぜ?', confidential: '守秘', confidentialDesc: 'NDA.', design: 'デザイン', designDesc: '貴社パッケージ', packaging: '包装', packagingDesc: 'オプション.', docs: '書類', docsDesc: '輸出.', oemProcess: ' 工程', inquiry: 'お問い合わせ', inquiryDesc: 'ご要望', sample: 'サンプル', sampleDesc: '承認', design2: 'デザイン', design2Desc: 'パッケージ', production: '生産', productionDesc: '生産完了', shipping: '出荷', shippingDesc: '世界へ', packagingOptions: '包装オプション', innerBox: 'インナーボックス', masterBox: 'マスターボックス', plastic: 'プラスチック', sizes: 'サイズ:', features: '特徴:', fullColor: 'フルカラー', lamination: 'ツヤ消し', embossing: 'エンボス', colorPrint: 'カラー', uv: 'UV', customSize: 'カスタム', heatSeal: 'ヒートシルク', zipLock: 'ジップ', standPouch: '立つポーチ', variousSizes: 'サイズ展開', customPrint: 'カスタム印刷', brandSafe: '保護', brandSafeDesc: 'NDA.', signedNDA: 'NDA', dedicatedLine: '生产线', designConf: '守秘', startBrand: 'ブランド開始', startBrandDesc: '貴社のブランドを.', contactOEM: 'お問い合わせ' },
    quality: { title: '品質 & 認定', subtitle: '信頼できる品質', cta: 'QC工程を見る', viewQC: 'QC工程を見る', requestReports: 'レポート請求', intCert: '国際認定', iso: 'ISO 9001:2015', isoDesc: '品質管理システム', exportLic: '輸出認定', exportLicDesc: 'インドネシア政府', factoryAudit: '工場監査', factoryAuditDesc: '第三者検証', msds: 'MSDS', msdsDesc: '安全データシート', qcProcess: '8ステップQC', qcProcessDesc: '一貫した品質', rawMaterial: '原料検査', rawMaterialDesc: '殻テスト', carbonization: '炭化', carbonizationDesc: '温度管理', grinding: '粉砕精度', grindingDesc: '正しいメッシュサイズ', mixing: '混合比率', mixingDesc: '正確な計量', pressing: '成型・プレス', pressingDesc: '油圧プレス', drying: '乾燥工程', dryingDesc: '管理乾燥', testing: '品質テスト', testingDesc: '灰分含有量', finalInspect: '最終検査', finalInspectDesc: '外観検査', labTesting: 'ラボテスト', labTestingDesc: '各バッチテスト', ashContent: '灰分含有量', ashContentDesc: '1.6% - 2.5%', moisture: '水分', moistureDesc: '4% - 8%', fixedCarbon: '固定炭素', fixedCarbonDesc: '75% - 80%', calorific: '熱量', calorificDesc: '7,500 カロリー/g', thirdParty: '第三者検査', thirdPartyDesc: 'SGS または Intertek', thirdPartyCTA: '輸出情報', reqDocs: '文書請求', reqDocsDesc: '各船出海レポート' },
    export: { title: '輸出 & 輸送', subtitle: '世界配送', cta: '輸送ルートを見る', viewShipping: '輸送ルートを見る', getQuote: '見積もり取得', country: '国', port: '港', transit: '輸送時間', containerType: 'コンテナタイプ', capacity: '内容量', dims: '寸法', prodTime: '生産・配送時間', prodTimeDesc: '標準リードタイム', loadingPort: '積込港', loadingPortDesc: 'ジャカルタ, スマラン, スрабャ', payment: '支払条件', paymentDesc: '柔軟なオプション', tt: '電信送金', ttDesc: '50% 前払い 50% 出船前', lc: '信用状',lcDesc: '10コンテナ以上', paymentDetails: 'USD, EUR 可能', docs: '輸出書類', doc1: '船荷証券', doc2: '請求書', doc3: '梱包リスト', doc4: '原産地証明書', doc5: '輸出宣言', doc6: 'MSDS', doc7: '品質証明書', moq: '最小注文数', moqDesc: '柔軟なサイズ', fcl: '20ftコンテナ', lcl: '1トン', fclDesc: '18-20トン', lclDesc: 'サンプル注文', readyOrder: '注文準備OK?', contactSales: '営業に連絡' },
    blog: { title: 'ブログ', subtitle: '記事とガイド', cta: '専門知識.', allPosts: '全記事', noArticles: '記事なし', checkBack: 'またきて!', stayUpdated: '最新情報を', stayUpdatedDesc: '購読して.', enterEmail: 'メール', subscribing: '購読中...', subscribe: '購読', success: 'ありがとう!', orContact: 'またはWhatsApp', privacy: 'プライバシー尊重.', readMore: '続きを読む', minRead: '分で読む' },
    keywords: ['シーシャ炭']
  }
};

export const getTranslation = (lang: Language): TranslationStrings => {
  return translations[lang] || translations.en;
};

export default translations;
